Guess number game
vadyukkha/inter-process_communication pull request #1
Opened 2024-11-19 16:19 UTC by vadyukkha

Реализованы функции межпроцессного взаимодействия;

Написана логика клиента для поиска заданного числа через бинарный поиск;

Написана логика сервера для устойчивой работы с пользователем;

2024-11-19 17:27 UTC, daniilparfenov requested changes

2024-11-19 17:27 UTC, daniilparfenov commented on guess_number/server.c
> +        sleep(3);
я бы уменьшил задержку, хотя для дебага удобно такую большую иметь

2024-11-19 17:27 UTC, daniilparfenov commented on guess_number/client.c
комментариев не хватает

2024-11-19 17:27 UTC, daniilparfenov commented on guess_number/client.c
> +        open_fds_connection(ptr_fds_write, FIFO_PATH, O_WRONLY);
Пока тестил, по-разному выключал то сервер, то клиента. Как я понял, на этом +- моменте клиент падает, если уронить сервер. Думаю, надо добавить обработку ошибки, т.е. внутри open_fds_connection не просто выкидывать ошибку, а либо прям там запустить цикл, который будет тыркаться, пытаясь открыть канал, либо прокинуть код ошибки -1 наверх и уже тут, в файле клиента, пытаться открывать канал. Если оставлять как щас, считай просто клиент падает, не обрабатывая эксепшн

2024-11-19 17:27 UTC, daniilparfenov commented on guess_number/server.c
- Нужны комменты
- Если я выключу клиента, который работает с сервером, сервер падает, даже не выводя никаких ошибок

2024-11-19 17:27 UTC, daniilparfenov commented on guess_number/server.c
> +        write_bytes_to_file(ptr_fds_write, msg);
На этом месте, если выключить клиента, сервер падает.  Хз почему, внутрянка во write не возвращает код ошибки, а тупо кладет программу, дебагер показывает это:
![image](https://github.com/user-attachments/assets/0d51c253-5bb9-4c37-86f8-7b379595bf88)

2024-11-19 19:21 UTC, daniilparfenov approved these changes

2024-11-22 17:41 UTC, LevPogromov approved these changes

2024-11-22 17:48 UTC, merged